### PR TITLE
Fix join room members issue

### PR DESCRIPTION
**Pull request by zxenonx**
Issue:  [L142](https://github.com/zurichat/zc_messaging/blob/38ab2585ec73222752f60f8d8a75505867d98f99/backend/endpoints/rooms.py#L142) and here [L145](https://github.com/zurichat/zc_messaging/blob/38ab2585ec73222752f60f8d8a75505867d98f99/backend/endpoints/rooms.py#L145)

We are comparing room_type to the RoomType values. But as the RoomType enum values are all in capital letters, the comparison fails when room_type is not in capital letters too. Same issue for Role enum (lowercase). As a result, the endpoint returns a 200 OK response but the new member is not added to the room_members dict.

Fix:
- change room_type and role respectively to uppercase and lowercase before comparison
- convert room_type to uppercase on Room schema validation

### CODE REVIEW

**Comment by zxenonx** [comment]
Thanks, @pauline-banye for reporting the issue.
@AI-fae 👍

**Review by mikenrowland — APPROVED** [review]
LGTM

**Review by FlorenceEgwu — CHANGES_REQUESTED** [review]
9 file changes?

Looks good though. 
well done! @zxenonx

**Review by paulinebanye — APPROVED** [review]
Good job boss @zxenonx .

**Review by FlorenceEgwu — APPROVED** [review]

**Comment by zxenonx** [comment]
> 9 file changes?
> 
> Looks good though. 
> well done! @zxenonx 

Sorry @AI-fae for the 9 changed files.
I didn't pull changes recently and some changes were not made by me but by the linter...

**Pull request merged**
