### PR TITLE
Feat/bac 26 trigger message events

### PR DESCRIPTION
**Pull request by matthew-akinola**
**This PR implements triggering of notifications when messages are sent.** 
The code changes do the following

Create a subscriber profile on the notification server to every member in a room when message is sent to that room
Publishes notification events to the notification server to be sent to the subscribers.
This builds on the work done in https://github.com/zurichat/zc_messaging/pull/141, https://github.com/zurichat/zc_messaging/pull/140 and https://github.com/zurichat/zc_messaging/pull/138, making notifications functional

**Note**
When a message notification is sent, Novu automatically subscribes the user if such user doesn't exist

### CODE REVIEW

**Comment by matthew-akinola** [comment]
@mikengr the messages.py file deletion and addition was a conflict github asked me to resolve, but in the real sense the only thing i added was import my file and instantiating the function handling the message triggering in my class. you can review

**Comment by mikengr** [comment]
Yeah that's why I needed a new PR, because you were working on your old merged branch.

**Comment by mikengr** [comment]
And it is still the same thing here. What you are doing is rewriting everyone's commit history on that file and I can't merge that.

**Comment by matthew-akinola** [comment]
What should I do instead? @mikengr 

what i did initially
checkout to dev branch, pull from dev branch, create a new branch from the dev and add my code, commit and make a PR before git indicated a conflict

**Pull request closed without merging**
