### PR TITLE
Linting and pre-commit-hook

### PR DESCRIPTION
**Pull request by austinoski**
Add linting and auto formatting with pylint and black
Add git pre-commit-hook to check backend project for linting errors.
Add auto setup pre-commit-hook to startup.sh script

Refactor code to get 10/10 score on pylint.

### CODE REVIEW

**Review by o4codes — CHANGES_REQUESTED** [review]
please change the uvicorn requiement in the requirement. txt file to uvicorn[standard] to make standard installation across different platforms.

**Review by zxenonx — APPROVED** [review]

**Comment by zxenonx** [comment]
> please change the uvicorn requiement in the requirement. txt file to uvicorn[standard] to make standard installation across different platforms.

ok. @austinoski

**Comment by austinoski** [comment]
Done and pushed. @o4codes

**Comment by zxenonx** [comment]
> Done and pushed. @o4codes

Also @austinoski is it possible to move all the lint.py, and all other things pertaining to backend linting to the backend folder .?

**Comment by austinoski** [comment]
Yeah, I think i can do that @zxenonx

**Comment by austinoski** [comment]
Done @zxenonx

**Review by o4codes — APPROVED** [review]

**Pull request merged**
