### PR TITLE
Test for send message endpoint

### PR DESCRIPTION
**Pull request by man-of-mind**
Test for send message endpoint with 5 test cases, pls review @o4codes @zxenonx @mykie88 @AI-fae

### CODE REVIEW

**Review by o4codes — APPROVED** [review]
Nice work @man-of-mind.
this gives us enough test case scenarios for the send_message endpoint.

**Review by FlorenceEgwu — APPROVED** [review]
Boss levels!

I am happy you are back! Well done @man-of-mind

**Comment by mikenrowland** [comment]
@zxenonx please can we merge this too. Thank you.

**Comment by zxenonx** [comment]
> @zxenonx please can we merge this too. Thank you.

Well, @man-of-mind and I were fixing an issue on the tests.
As soon as it's okay, we will merge this PR.
@mykie88

**Review by zxenonx — APPROVED** [review]

**Pull request merged**
