### PR TITLE
Feat/bac 26 trigger message event

### PR DESCRIPTION
**Pull request by matthew-akinola**
This PR implements triggering of notifications when messages are sent.
The code changes do the following

Create a subscriber profile on the notification server when a person joins a room
Publishes notification events to the notification server to be sent to the subscribers.
This builds on the work done in https://github.com/zurichat/zc_messaging/pull/141, https://github.com/zurichat/zc_messaging/pull/140 and https://github.com/zurichat/zc_messaging/pull/138, making notifications functional

### CODE REVIEW

**Comment by a11rew** [comment]
This PR implements triggering of notifications when messages are sent. 
The code changes do the following
- Create a subscriber profile on the notification server when a person joins a room
- Publishes notification events to the notification server to be sent to the subscribers.

This builds on the work done in #141, #140 and #138, making notifications functional.

**Comment by a11rew** [comment]
@zxenonx @mikengr @AI-fae review please.

**Comment by mikengr** [comment]
@matthew-akinola Your PR doesn't have a description

**Comment by matthew-akinola** [comment]
> @matthew-akinola Your PR doesn't have a description

@mikengr check again

**Review by mikengr — APPROVED** [review]
LGTM

**Comment by mikengr** [comment]
@matthew-akinola resolve conflicts please

**Comment by mikengr** [comment]
Also please avoid using a merged branch for making new changes. Once a branch is merged, subsequent new changes should be done on a new branch

**Comment by matthew-akinola** [comment]
> Also please avoid using a merged branch for making new changes. Once a branch is merged, subsequent new changes should be done on a new branch

noted!! Conflict resolved @mikengr

**Comment by mikengr** [comment]
Move these changes to a new PR

**Pull request closed without merging**
