### PR TITLE
Fix/bac 49 custom pagination

### PR DESCRIPTION
**Pull request by Shopiley**
Implemented suggestions from reviewers of last pull request.
Added more pagination information to response for frontend to consume such as:
1. total number of items in db
2. pointer to the next page
3. pointer to the previous page
with @bolexs 

[Linear Link](https://linear.app/team-gear/issue/BAC-49/zuri-chat-task)

image

Please review:
@AI-fae @mikengr  @zxenonx

### CODE REVIEW

**Review by mikengr — COMMENTED** [review]
Great work! You have conflicts to resolve though

**Comment by Shopiley** [comment]
> Great work! You have conflicts to resolve though

I’ve resolved them

**Comment by mikengr** [comment]
You still have conflicts @Shopiley

**Comment by Shopiley** [comment]
> You still have conflicts @Shopiley

Fixed again @mikengr (someone reverted their commit so I had to revert the changes I made to fix the previous merge conflict).

**Review by mikengr — CHANGES_REQUESTED** [review]
@Shopiley `messages.py` file was completely rewritten just to make few changes? this will automatically mess up the commit history of this file. Please close this PR, create a new branch from dev, move your changes there and make a new PR. Thanks.

**Pull request closed without merging**
