### PR TITLE
Feat: FRO-76/ Create a new thread through reply Icon

### PR DESCRIPTION
**Pull request by Mavrik-jnr**
This adds a comment board when thread is opened
Linear-Ticket: https://linear.app/team-bevel/issue/FRO-76/create-a-new-thread-through-reply-icon-right
https://user-images.githubusercontent.com/60897319/203923263-2518d63b-7265-491c-b89b-d2951a60b502.mp4

### CODE REVIEW

**Comment by JulianaSau** [comment]
Hi @Mavrik-jnr, please include a screenshot or video to support this change

**Comment by JulianaSau** [comment]
@zxenonx review this with me😁

**Comment by Mavrik-jnr** [comment]
https://user-images.githubusercontent.com/60897319/203923263-2518d63b-7265-491c-b89b-d2951a60b502.mp4

@JulianaSau

**Review by ickynavigator — CHANGES_REQUESTED** [review]
Include a vid of you actually creating a thread not navigating to it manually with a url

**Comment by Mavrik-jnr** [comment]
> Include a vid of you actually creating a thread not navigating to it manually with a url 
@ickynavigator 

The Chat api currently down, so messages aren't being rendered. the Message pane with reply icon isn't rendered as a result
error

once it's up, i'll update the video, Thanks

**Comment by Mavrik-jnr** [comment]
@ickynavigator @JulianaSau Please Review

https://user-images.githubusercontent.com/60897319/204021408-bab0f32f-f350-413b-87ea-d388f1cfde1c.mp4

**Review by ickynavigator — APPROVED** [review]
LGTM

**Comment by ickynavigator** [comment]
@JulianaSau i've approved

**Review by JulianaSau — APPROVED** [review]

**Pull request merged**
