### PR TITLE
Setup Airbnb linting rules for react and pre-commit hooks for frontend and backend

### PR DESCRIPTION
**Pull request by NdubuisiJr**
PS: There are a lot of file changes (18) because I had to fix the linting errors before I can commit. That's what the pre-commit does to you.

### CODE REVIEW

**Review by mukhtarB — CHANGES_REQUESTED** [review]
Why are you on the backend folder sir, I can see you editted the pylint also.

**Comment by o4codes** [comment]
There are a lot of changes made. The former pre-commit worked, which I still don't know why it was removed.  The working procedure we ensured before was to ensure backend dev only worked in the backend folder and frontend dev only worked in the FE dev in order to avoid complications, but with this the whole project folder has to be opened.

**Comment by NdubuisiJr** [comment]
@o4codes @mukhtarB please watch this
https://www.loom.com/share/58c3071a00ea46aeb2f20d91881021fe

**Comment by NdubuisiJr** [comment]
I finally added a .flake8 config file to increase the length of the characters

**Comment by o4codes** [comment]
Nice work @NdubuisiJr 
Can you please add one little thing.
Inside the backend folder can you leave the pre-commit-config.yaml

Then inside the husky precommit for backend just cd into backend and run "pre-commit".
I'm suggesting this so that over time whatever additions or removals we need to concerning backend linting we just need to touch the pre-commit-config.yaml.

But this is great work.

**Comment by NdubuisiJr** [comment]
image

for the setup. All the backend or frontend person need to do is `run yarn setup` or `npm run setup` from the root folder

**Comment by NdubuisiJr** [comment]
@o4codes I've set it up as you requested.

**Comment by o4codes** [comment]
@benjamin-bala 
Please review

**Review by benjamin-bala — COMMENTED** [review]
@o4codes everything looks okay. but 1 question would the pre commit get to affect the whole file every time?? or just the part one worked on

**Comment by o4codes** [comment]
Well basically all files it has an issue with.
The main issue is python backend dev having to install node and yarn @benjamin-bala

**Comment by benjamin-bala** [comment]
Is there any other solution?? @o4codes

**Comment by zxenonx** [comment]
Thanks @NdubuisiJr for the work.
However, this setup fits more for your plugin than ours. In chess plugin, your stack is React/Node. Here, as you can see, we are using python for the backend. But now, with this setup, because of linting, a backend dev has to run a node cmd. Why ? I don't really  think this setup is the best for us.
In our previous linting setup, the linting settings related to python lived in the backend folder. And the same thing could be done for the frontend.
@o4codes @benjamin-bala

**Comment by NdubuisiJr** [comment]
@zxenonx  there’s nothing wrong with a backend developer installing and running yarn or a frontend developer installing python and running pip.

Don’t forget it’s an open source project, each commit needs to be validated on both ends of the spectrum. If we start writing test, all tests (frontend and backend) needs to be run before any other thing happens. Both tests/lint needs to run and be validated. 

Please check other open source full stack projects. To even contribute you need to have all environments setup properly.

**Comment by zxenonx** [comment]
> @zxenonx  there’s nothing wrong with a backend developer installing and running yarn or a frontend developer installing python and running pip.
> 
> Don’t forget it’s an open source project, each commit needs to be validated on both ends of the spectrum. If we start writing test, all tests (frontend and backend) needs to be run before any other thing happens. Both tests/lint needs to run and be validated. 
> 
> Please check other open source full stack projects. To even contribute you need to have all environments setup properly.

Thanks for your reply. Maybe we'll set a meeting to talk more about it.

**Comment by mukhtarB** [comment]
@NdubuisiJr pls can you repush the pr to contain just linting for now, so this doesnt hold us back much longer.

**Comment by NdubuisiJr** [comment]
@mukhtarB I've removed the pre-commit stuff. All we have now is linting

**Comment by mukhtarB** [comment]
okay boss, pls can you get someone in FE to review so we can merge the PR, it's been opened too long, also pls pull new changes

**Review by mukhtarB — APPROVED** [review]

**Pull request closed without merging**
