### PR TITLE
add plugin-id

### PR DESCRIPTION
**Pull request by Delight-Fela-Steve**
Registered the plugin and included the plugin id in db.py

### CODE REVIEW

**Review by mukhtarB — APPROVED** [review]

**Review by mukhtarB — COMMENTED** [review]
pls what's delaying this pr @zxenonx @o4codes @man-of-mind

**Review by man-of-mind — APPROVED** [review]

**Comment by mukhtarB** [comment]
@Delight-Fela-Steve  can you pull changes to update PR?

**Comment by Delight-Fela-Steve** [comment]
On it

**Comment by Delight-Fela-Steve** [comment]
Changes pulled

**Review by zxenonx — APPROVED** [review]

**Pull request merged**
