### PR TITLE
startup.sh script refactored

### PR DESCRIPTION
**Pull request by o4codes**
startup.sh script has been refactored to use both venv and pipenv

to use venv 
sh startup.sh venv

to use pipenv
sh startup.sh pipenv

@mukhtarB 
@zxenonx 
@Delight-Fela-Steve 
@man-of-mind

### CODE REVIEW

**Review by man-of-mind — APPROVED** [review]
Well done boss, what happens when u already have a virtual environment set up with a different name aside venv on a linux?
If u create a new virtual environment, will everything be okay? I mean no conflict between the two virtual environments.

**Comment by o4codes** [comment]
The venv is just a name.
If you don't have any virtual environment activated the script will not proceed

**Comment by o4codes** [comment]
Further improvements will be made to search for existing virtual environment in the folder and use them

**Comment by man-of-mind** [comment]
Oh....okay, nice
Well done boss.

**Comment by zxenonx** [comment]
> Well done boss, what happens when u already have a virtual environment set up with a different name aside venv on a linux?
> If u create a new virtual environment, will everything be okay? I mean no conflict between the two virtual environments.

@man-of-mind, I think in ```
sh startup.sh venv
```, venv is actually a name. Your env folder could be backend-env or env, it doesn't matter, because the name of your virtual env folder is not used in the script. @o4codes, right?

**Review by zxenonx — APPROVED** [review]

**Comment by man-of-mind** [comment]
@o4codes @zxenonx I don't think there will be any problem even with existing virtual environment, a new environment should be created (venv) and then start it, so far it's the venv that is started and not the other one.

**Comment by o4codes** [comment]
Well.
For future improvement the script will be made to check for any virtual environment in the present working directory and use that virtual environment.

**Comment by man-of-mind** [comment]
Well done boss @o4codes 
U be baba

**Pull request merged**
