### PR TITLE
Refactor test_messages.py

### PR DESCRIPTION
**Pull request by zxenonx**
Fixes https://linear.app/zurichat2/issue/ZUR-81/refactor-test-messagespy

Run `pytest tests/endpoints/test_message.py -vv --cov` to test this PR as the changes made to the fixtures have not been applied to the other tests (they will fail).

### CODE REVIEW

**Review by man-of-mind — COMMENTED** [review]
Good work boss @zxenonx some of this changes will affect other tests using these fixtures, we need to refactor them as well

**Comment by zxenonx** [comment]
> Good work boss @zxenonx some of this changes will affect other tests using these fixtures, we need to refactor them as well

The room tests right? @man-of-mind
For this PR, I've ignored all the tests except the ones for the messages.

**Comment by man-of-mind** [comment]
> > Good work boss @zxenonx some of this changes will affect other tests using these fixtures, we need to refactor them as well
> 
> The room tests right? @man-of-mind 

Yes boss @zxenonx all the tests are using the fixtures, we can use just use find and replace tho

**Comment by zxenonx** [comment]
> > > Good work boss @zxenonx some of this changes will affect other tests using these fixtures, we need to refactor them as well
> > 
> > The room tests right? @man-of-mind 
> 
> Yes boss @zxenonx all the tests are using the fixtures, we can use just use find and replace tho

I'll fix it. Thanks.

**Comment by zxenonx** [comment]
@man-of-mind, I think for the room tests refactoring, I'll wait a bit. There's even a pending PR on a room test...
I've updated the description of this PR.

**Comment by man-of-mind** [comment]
> @man-of-mind, I think for the room tests refactoring, I'll wait a bit. There's even a pending PR on a room test...
> I've updated the description of this PR.

Alright boss

**Pull request merged**
