### PR TITLE
feat(BAC-79)  add get channel details endpoint and feat(BAC-80) delete channel endpoint

### PR DESCRIPTION
**Pull request by jujucoder**
https://linear.app/team-bevel/issue/BAC-79/create-a-delete-channel-endpoint
Add get channel details endpoint in backend/endpoints/rooms.py  : 
(GET) /org/{org_id}/rooms/{room_id} that retrieves details of a room

add delete channel endpoint in backend/endpoints/rooms.py : 
(DELETE) /org/{org_id}/rooms/{room_id} that deletes a room

add function in backend/utils/room_utils.py that sends a request to zuri_core to delete a room

### CODE REVIEW

**Review by billmal071 — APPROVED** [review]

**Comment by mikengr** [comment]
@billmal071 you merged this PR without a review, is there a reason for that please?

**Comment by billmal071** [comment]
> @billmal071 you merged this PR without a review, is there a reason for that please?

I reviewed, did you find any issues?

**Comment by billmal071** [comment]
@jayjaytentacion You need to check for room type so that only channel rooms can be deleted.

**Comment by jujucoder** [comment]
> @jayjaytentacion You need to check for room type so that only channel rooms can be deleted.

Let me do that right now and make a new pull request

**Pull request merged**
